"""Initiele schema — alle tabellen zoals ze bestonden vóór Alembic (create_all-tijdperk).

Revision ID: 0001
Revises: None
Create Date: 2026-08-26
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotatie_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_slug', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('actie', sa.String(length=64), nullable=False),
    sa.Column('element_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tijdstip', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotatie_audit_doc_id', 'annotatie_audit', ['document_slug', 'id'], unique=False)
    op.create_table('annotatie_documenten',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('citeertitel', sa.Text(), nullable=False),
    sa.Column('werkgebied', sa.Text(), nullable=False),
    sa.Column('bwbId', sa.String(length=64), nullable=False),
    sa.Column('artikel', sa.String(length=32), nullable=False),
    sa.Column('lid', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('elementen', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('runs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index('ix_annotatie_docs_user_updated', 'annotatie_documenten', ['user_id', 'updated'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('bericht_leesbewijzen',
    sa.Column('bericht_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=64), nullable=False),
    sa.Column('gelezen_op', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bericht_id', 'userid')
    )
    op.create_table('berichten',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titel', sa.Text(), nullable=False),
    sa.Column('inhoud', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('versie', sa.String(length=32), nullable=True),
    sa.Column('gepubliceerd', sa.Boolean(), nullable=False),
    sa.Column('gepubliceerd_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aangemaakt_door', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_berichten_gepubliceerd_created', 'berichten', ['gepubliceerd', 'created'], unique=False)
    op.create_table('gesprek_berichten',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gesprek_id', sa.String(length=64), nullable=False),
    sa.Column('rol', sa.String(length=16), nullable=False),
    sa.Column('inhoud', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gesprek_berichten_gesprek', 'gesprek_berichten', ['gesprek_id', 'id'], unique=False)
    op.create_table('gesprekken',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('titel', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gesprekken_user_updated', 'gesprekken', ['user_id', 'updated'], unique=False)
    op.create_table('llm_profiles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('api_base', sa.String(length=512), nullable=False),
    sa.Column('api_version', sa.String(length=64), nullable=True),
    sa.Column('output_strategy', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('enc_api_key', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('userid', sa.String(length=128), nullable=False),
    sa.Column('categorie', sa.String(length=32), nullable=False),
    sa.Column('tekst', sa.Text(), nullable=False),
    sa.Column('pagina', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_feedback_created', 'user_feedback', ['created'], unique=False)
    op.create_table('users',
    sa.Column('userid', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('totp_secret_enc', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback_gezien_op', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('ix_user_feedback_created', table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_table('llm_profiles')
    op.drop_index('ix_gesprekken_user_updated', table_name='gesprekken')
    op.drop_table('gesprekken')
    op.drop_index('ix_gesprek_berichten_gesprek', table_name='gesprek_berichten')
    op.drop_table('gesprek_berichten')
    op.drop_index('ix_berichten_gepubliceerd_created', table_name='berichten')
    op.drop_table('berichten')
    op.drop_table('bericht_leesbewijzen')
    op.drop_table('api_tokens')
    op.drop_index('ix_annotatie_docs_user_updated', table_name='annotatie_documenten')
    op.drop_table('annotatie_documenten')
    op.drop_index('ix_annotatie_audit_doc_id', table_name='annotatie_audit')
    op.drop_table('annotatie_audit')
    # ### end Alembic commands ###
