"""Het JobStore-Protocol — de opslag-abstractie waarop de engine en routers typeren.

Zo is de bron-van-state vervangbaar en mockbaar zonder aan één concrete implementatie vast te
zitten (vgl. het LLMClient-protocol in llm/base.py). De huidige implementatie is PostgresStore
(SQLAlchemy/PostgreSQL); een andere backend hoeft enkel dit protocol na te komen.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .contracts import Analyse2, Analyse3, Feedback, Job, JobState
from .project import Project, RondeData


class IdConflict(Exception):
    """Kon na meerdere pogingen geen vrije slug reserveren — gelijktijdige identieke aanmaak."""


@runtime_checkable
class JobStore(Protocol):
    # --- id-afleiding (seed = werkgebied-naam of een afgeleide van de eerste bron) ---
    async def afgeleid_id(self, seed: str) -> str: ...

    # --- job (state-machine view) ---
    async def save_job(self, job: Job, *, owner: str | None = None) -> bool: ...
    async def set_current_fase(self, job_id: str, fase: str | None, owner: str) -> bool: ...
    async def insert_job(self, job: Job, *, max_active: int = 0) -> None: ...
    async def create_project(self, project: Project, *, max_active: int = 0) -> None: ...
    async def load_job(self, job_id: str) -> Job | None: ...
    async def list_jobs(self, client_id: str | None = None) -> list[Job]: ...

    # --- concurrency (state-CAS; vervangt de in-process lock) ---
    async def claim(
        self, job_id: str, van: set[JobState], naar: JobState, owner: str, lease_s: int,
        *, vereist_verlopen_lease: bool = False,
    ) -> Job | None: ...
    async def verleng_lease(self, job_id: str, owner: str, lease_s: int) -> bool: ...
    async def lijst_verlopen_running(self) -> list[str]: ...
    async def lijst_verweesde_queued(self, ouder_dan_s: int) -> list[str]: ...
    async def markeer_lease_loze_running(self) -> int: ...

    # --- analyse (immutabel per ronde) ---
    async def hoogste_ronde(self, job_id: str, activiteit: str) -> int: ...
    async def schrijf_analyse(self, job_id: str, activiteit: str, ronde: int, data: dict) -> None: ...
    async def lees_analyse(self, job_id: str, activiteit: str, ronde: int) -> dict | None: ...
    async def lees_analyse_model(
        self, job_id: str, activiteit: str, ronde: int
    ) -> Analyse2 | Analyse3 | None: ...
    async def lees_alle_rondes(self, job_id: str, activiteit: str) -> dict[str, RondeData]: ...

    # --- feedback ---
    async def schrijf_feedback(self, job_id: str, activiteit: str, ronde: int, fb: Feedback) -> None: ...
    async def lees_feedback(self, job_id: str, activiteit: str, ronde: int) -> Feedback | None: ...

    # --- rapport ---
    async def schrijf_rapport(self, job_id: str, rapport: dict) -> None: ...
    async def lees_rapport(self, job_id: str) -> dict | None: ...

    # --- regelspraak-model (eigen artefact náást het rapport) ---
    async def schrijf_regelspraak(self, job_id: str, model: dict) -> None: ...
    async def lees_regelspraak(self, job_id: str) -> dict | None: ...

    # --- LLM-call-capture (prompt + ruwe respons, voor analyse) ---
    async def schrijf_llm_call(self, call: dict) -> None: ...
    async def lijst_llm_calls(self, project_slug: str) -> list[dict]: ...

    # --- generieke runtime-instellingen (key/value) ---
    async def lees_app_setting(self, key: str): ...
    async def schrijf_app_setting(self, key: str, value) -> None: ...

    # --- project CRUD ---
    async def load_project(self, job_id: str) -> Project | None: ...
    async def list_projects(
        self, client_id: str | None = None, *, limit: int | None = None, offset: int = 0,
        light: bool = False,
    ) -> list[Project]: ...
    async def delete_project(self, job_id: str) -> bool: ...
